example:
  url_template: http://server:8080/{{.string_param}}/{{.int_param}}
  parameters:
    query_int:
      help: param to demonstrate <b>int</b> param in query
      name: query_int
      destination: query
      type: integer
    query_string:
      help: param to demonstrate string <b>param</b> in query
      name: query_string
      destination: query
      type: string
      optional: true
    int_param:
      help: param to demonstrate <b>integer</b> params in <b>url</b>
      name: int_param
      destination: URL
      type: integer
    string_param:
      help: param to demonstrate <b>string</b> param in <b>url</b>
      name: string_param
      destination: URL
      type: string
      default_value: default_value_str
  body: "
  <b>URL requested</b> :\n {{.meta.url}}
  \n
  <b>params</b> :\n
  {{ range $key, $value := .meta.params }} <b>{{ $key }}</b> : {{ $value }} \n {{ end }}
  \n
  <b>responce</b> :\n
  {{ range $key, $value := .responce }} <b>{{ $key }}</b> : {{ $value }} \n {{ end }}
  "
  url_name: example
  help: "simple example hand"