version: "3.3"
services:
  bot:
    build: ..
    volumes:
      - ../example/whitelist.json:/HandWitch/whitelist.json 
      - ./descriptions_compose.yaml:/HandWitch/descriptions.yaml 
      - ./crt:/crt/
      - ./utils:/HandWitch/utils/
      - ./config_hook_part.json:/HandWitch/config_hook_part.json
      - ./config_template.json:/HandWitch/config_template.json
    ports:
      - "8443:8443"
  server:
    build: ../example
    ports:
      - "8080:8080"
