version: "3.3"
services:
  bot:
    restart_policy: 
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    image: glazedcurd/handwitch
    volumes:
      - ./whitelist.json:/HandWitch/whitelist.json
      - ./descriptions_compose.yaml:/HandWitch/descriptions.yaml
      - ./crt:/crt/
    environment:
      - TELEGRAM_BOT_SSL_PUB_NAME
      - TELEGRAM_BOT_SSL_PRIV_NAME
      - HANDWITCH_USE_WEBHOOK
      - HANDWITCH_TELEGRAMM_TOKEN
    ports:
      - "8443:8443"
  server:
    restart_policy: 
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    image: glazedcurd/handwitchexampleserver
    ports:
      - "8080:8080"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30