version: "3.3"
services:
  bot:
    build: ..
    volumes:
      - ../example/config.json:/config.json 
      - ../example/whitelist.json:/HandWitch/whitelist.json 
      - descriptions-compose.yaml:/HandWitch/descriptions.yaml 
      - crt:/crt/
    ports:
      - "8443:8443"
    env_file:
      - "params.env"
  server:
    build: ../example
    ports:
      - "8080:8080"
volumes: 
  crt: