language: go

go: 
- 1.13.x

env:
  - GO111MODULE=on
    GOFLAGS="-mod=vendor"

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - GOFLAGS="" go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...