name: compose_file_deploy
on:
  push:
    branches:
    - master
    paths:
    - compose_example/docker-compose.yml
jobs:
  deploy_compose:
    name: deploy_compose
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send new compose file on server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.KEY_PASS }}
        port: ${{ secrets.PORT }}
        source: "compose_example/docker-compose.yml"
        target: "/projects/HandWitch/compose_example/docker-compose.yml"
        strip_components: 1
    - name: apply compose file
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.KEY_PASS }}
        port: ${{ secrets.PORT }}
        script: |
          cd /projects/HandWitch/compose_example
          docker-compose pull
          TELEGRAM_BOT_SSL_PUB_NAME=YOURPUBLIC.pem \
          TELEGRAM_BOT_SSL_PRIV_NAME=YOURPRIVATE.key \
          HANDWITCH_USE_WEBHOOK=${{ secrets.HANDWITCH_USE_WEBHOOK }} \
          HANDWITCH_TELEGRAMM_TOKEN=${{ secrets.HANDWITCH_TELEGRAMM_TOKEN }} \
          docker-compose up -d --force-recreate

